### ISSUE TITLE
can't run file without prefix

### ISSUE THREAD

**Issue by antifarben** [opal/opal-node#10]
If I want to execute a file in the current directory it won't work without prefix (ie `$ opal-node test.rb`) will result in something like

``` bash
  LoadError: cannot load such file -- test.rb
```

while it will run fine if I set a relative path prefix (ie `$ opal-node ./test.rb`)

**Comment by jwoertink** [comment]
I'm getting this error as well.

**Comment by elia** [comment]
Node support is now backed right into opal: `opal -rnodejs -e 'puts "hello node!"'`
