### ISSUE TITLE
readme mentions compiling coffee script - a typo, I presume...

### ISSUE THREAD

**Issue by kimptoc** [opal/opal-node#2]
.

**Comment by elia** [comment]
The only mention I found refers to developing/testing opal-node itself.
For that task you need to have coffeescript installed as it's used in the code that loads opal files.

Any suggestion on rephrasing those sentences is welcome :)

**Comment by kimptoc** [comment]
Oops - sorry, missed the big heading above it, saying "Developing" - I thought it was about developing with opal-node, not developing opal-node itself :(
