### ISSUE TITLE
More examples in Readme?

### ISSUE THREAD

**Issue by StephenOTT** [opal/opal-node#8]
Would it be possible to get a few more examples in the read me?

**Comment by elia** [comment]
You would like to see anything in particular?

**Comment by StephenOTT** [comment]
Would love to see a very simple non-gui app.  Just something to walk through the process of setting up the server.  Setting up routes on the node server and then calling those commands from the browser and displaying the output in the console and/or in html.

**Comment by StephenOTT** [comment]
@elia Thanks!!! I will review and test with the example a little.  May come back with a few additions, but i think its a great start to bringing more adoption.

What about a AngularJS example?  node and angular are the two i keep running into.  Would be great to get a angular examples.  May not be the spot in the Node repo but maybe another repo?

@elia Thoughts?

**Comment by elia** [comment]
@StephenOTT great!

About angular I'm sorry but it's quite out of the games (opal/opal#400) for now.
Any example that is not nodejs specific should go to [opal/opal](/opal/opal)
